name: Update SingBox Rules

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours

jobs:
  download-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create target directory
        run: mkdir -p meta-rules-dat-sing

      - name: Download .srs files
        run: |
          curl -L -o meta-rules-dat-sing/category-ads-all.srs https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs
          curl -L -o meta-rules-dat-sing/private-geosite.srs https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/private.srs
          curl -L -o meta-rules-dat-sing/category-ir.srs https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ir.srs
          curl -L -o meta-rules-dat-sing/private-geoip.srs https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/private.srs
          curl -L -o meta-rules-dat-sing/ir-geoip.srs https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/ir.srs

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add meta-rules-dat-sing/
          git commit -m "Update meta-rules-dat-sing files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
