name: Update SingBox Rules (Paths)

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:       # manual trigger

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download files
        run: |
          mkdir -p armv8
          curl -L -o armv8/wp-caa.srs "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs"
          curl -L -o armv8/wp-pgs.srs "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/private.srs"
          curl -L -o armv8/wp-ci.srs "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ir.srs"
          curl -L -o armv8/wp-pgp.srs "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/private.srs"
          curl -L -o armv8/wp-ir.srs "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/ir.srs"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add meta-rules-dat-sing/*
          git commit -m "Update meta-rules-dat-sing files" || echo "No changes to commit"
          git push
